### ISSUE TITLE
Kotlin artifacts off by one directory

### ISSUE THREAD

**Issue by hzsweers** [square/osstrich#18]
The generated index.html currently doesn't seem to register Dokka-generated javadoc jars correctly

See this for what it outputs:

https://github.com/uber/AutoDispose/commit/54dcaac1803a483899d38f5e44d9e1b123555dbf

For example - the `autodispose-kotlin` artifact is linked as 

https://uber.github.io/AutoDispose/0.x/autodispose-kotlin/

but should actually be

https://uber.github.io/AutoDispose/0.x/autodispose-kotlin/autodispose-kotlin/

It seems the first layer is just metadata for the site?

<img width="446" alt="screen shot 2017-12-03 at 11 24 41 pm" src="https://user-images.githubusercontent.com/1361086/33540715-30958c38-d881-11e7-9134-e8ef13fbe33e.png">

**Comment by hzsweers** [comment]
If it is just the one level deeper, I can open a PR to do that on kotlin docs. Let me know what you think. I'll double check on the details for dokka as well

**Comment by hzsweers** [comment]
Looking more... I don't see any information that makes it obvious without doing some grepping through the downloaded directory. 

Only promising thing I see right now is to:
1. Check if there's an immediate subdirectory of the same artifact ID name
2. Check if that subdirectory has the `package-list` file in it
3. (probably unnecessary) - peek the `package-list` file and see if it contains `$dokka` in it

**Comment by swankjesse** [comment]
But the CSS is in the right place? Hmm.

We have something reasonable for KotlinPoet, but it doesn't have a parent module.

https://square.github.io/kotlinpoet/0.x/kotlinpoet/com.squareup.kotlinpoet/

**Comment by swankjesse** [comment]
Should this be fixed in KDoc?

**Comment by charlesdurham** [comment]
Yeah, seems odd that the CSS is at the root but the index file is nested. Found this semi-related (basically the inverse) issue: https://github.com/Kotlin/dokka/issues/163

**Comment by hzsweers** [comment]
That issue makes me think the directory structure is intentional if there's multiple modules
