### ISSUE TITLE
--dry-run

### ISSUE THREAD

**Issue by JakeWharton** [square/osstrich#9]
Does everything but commit and push.

**Comment by swankjesse** [comment]
Maybe even commit without pushing?

**Comment by JakeWharton** [comment]
Seems potentially dangerous. Maybe just prints the commands?

**Comment by swankjesse** [comment]
It’s committing to a private copy of the repo, so the potential damage is low.

**Comment by swankjesse** [comment]
We should probably name the temporary directory something unguessable with a UUID to further prevent pushes or reuse of that directory.
